#!/bin/bash

#  https://tidesandcurrents.noaa.gov/api/datagetter?begin_date=20130101 10:00&end_date=20130101 10:24&station=8454000&product=water_level&datum=mllw&units=metric&time_zone=gmt&application=web_services&format=xml 

date="latest"
station="8418150"

# product="water_temperature"
product="water_level"
# product="high_low"

datum="mllw"
units="english"

# time_zone="lst"
time_zone="lst_ldt"

# format="csv"
format="json"

application="tide-viewer-v0.1-granola"

base_url="https://tidesandcurrents.noaa.gov/api/datagetter"

url="$base_url?date=$date&station=$station&product=$product&datum=$datum&units=$units&time_zone=$time_zone&format=$format&application=$application"

echo "$url" >&2

curl -Ss "$url"
